name: test
on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: yarn install
        run: yarn
      - name: yarn lint:all
        run: yarn lint:all
      - name: yarn compile
        run: yarn compile
      - name: yarn test
        run: yarn test

